esphome:
  name: quatt-sniffer
  friendly_name: Quatt sniffer

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: !secret api

ota:
  - platform: esphome
    password: !secret ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

substitutions:
  throttling_value: 10s    ##When set to 0s, new reading every second!
  uart_rx_pin: GPIO20     ## on ESP32C3 use GPIO20, on ESP32 use GPIO23

packages:
  HP1:
    url: https://github.com/M10tech/Quatt-sniffer
    files: [quatt-sniffer-HP1.yaml]
  ##Uncomment lines below in case you have a Quatt Duo
  # HP2:
  #   url: https://github.com/M10tech/Quatt-sniffer
  #   files: [quatt-sniffer-HP2.yaml]

